### ISSUE TITLE
[FEATUER] 관리자 도메인, 카테고리 기능

### ISSUE THREAD

**Issue by kwj0605** [peopleofF4/peopleofF#4]
## Description
관리자 도메인의 기능 및 카테고리 기능을 생성한다.
## To-do
- [ ] 회원 전체 조회
- [ ] 회원 삭제
- [ ] 카테고리 생성
- [ ] 카테고리 수정
- [ ] 가게 등록 승인/거부
- [ ] 가게 삭제 승인/거부
- [ ] 유저 검색
- [ ] 유저 권한 수정
- [ ] 매니저 등록 승인
## 작업 내용
설명
